// Indonesian names for the room facilities in src/data/kamar.json.
// Add a line here whenever a new facility is added to kamar.json.
export const facilitiesId: Record<string, string> = {
  "King bed": "Kasur king",
  "Garden view": "Pemandangan taman",
  "Rain shower": "Rain shower",
  "Air conditioning": "AC",
  "Free Wi-Fi": "Wi-Fi gratis",
  '43" smart TV': 'Smart TV 43"',
  "Coffee & tea maker": "Pembuat kopi & teh",
  Minibar: "Minibar",
  "In-room safe": "Brankas di kamar",
  Hairdryer: "Pengering rambut",
  "Sea view": "Pemandangan laut",
  "Work desk": "Meja kerja",
  "Private balcony": "Balkon pribadi",
  "Separate living area": "Ruang duduk terpisah",
  "Bathtub & rain shower": "Bathtub & rain shower",
  "Espresso machine": "Mesin espresso",
  '55" smart TV': 'Smart TV 55"',
  "Bathrobes & slippers": "Jubah mandi & sandal",
  "Daily turndown service": "Layanan turndown setiap malam",
  "Two queen beds": "Dua kasur queen",
  "Stone walls": "Dinding batu alam",
  Bathtub: "Bathtub",
  "Garden terrace": "Teras taman",
  "Sofa bed": "Sofa bed",
  '50" smart TV': 'Smart TV 50"',
  "Mini fridge": "Kulkas mini",
  "Kids' amenities": "Perlengkapan anak",
  "Connecting room on request": "Kamar terhubung (sesuai permintaan)",
};
